// app/routes/password-reset.tsx
import type { ActionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import { Link, useActionData, useTransition } from "@remix-run/react";
import { withZod } from "@remix-validated-form/with-zod";
import { sendPasswordResetEmail } from "firebase/auth";
import { ValidatedForm, validationError } from "remix-validated-form";
import { z } from "zod";
import { SubmitButton } from "~/components/submit-button";
import { TextField } from "~/components/text-field";
import { P } from "~/components/typeography/p";
import {
  AuthCard,
  AuthCardActions,
  AuthCardBody,
  AuthCardLinks,
  AuthCardTitle,
} from "~/features/auth";
import { auth } from "~/lib/firebase";

const validator = withZod(
  z.object({
    email: z
      .string()
      .min(1, { message: "Email is required." })
      .email("Must be a valid email."),
  })
);

export async function action({ request }: ActionArgs) {
  const formData = await request.formData();
  const result = await validator.validate(formData);

  if (result.error) {
    return validationError(result.error);
  }

  const { email } = result.data;

  await sendPasswordResetEmail(auth, email);

  return json({
    successMessage: "Please check your email for a reset password link.",
  });
}

export default function PasswordReset() {
  const { submission } = useTransition();
  const data = useActionData<typeof action>();

  if (data && "successMessage" in data) {
    return (
      <AuthCard>
        <AuthCardBody>
          <P className="alert alert-info shadow-lg mb-3">
            {data.successMessage}
          </P>

          <div className="flex justify-end gap-1">
            <Link className="link hover:link-primary" to="/sign-in">
              Sign In
            </Link>
            or
            <Link className="link hover:link-primary" to="/sign-up">
              Sign Up
            </Link>
          </div>
        </AuthCardBody>
      </AuthCard>
    );
  }

  return (
    <AuthCard>
      <AuthCardBody>
        <ValidatedForm validator={validator} method="post">
          <AuthCardTitle>Reset Password</AuthCardTitle>

          <TextField name="email" type="email" label="Email" />

          <AuthCardActions>
            <SubmitButton
              isLoading={Boolean(submission)}
              disabled={Boolean(submission)}
            >
              {submission ? "Sending Reset Email..." : "Reset Password"}
            </SubmitButton>

            <AuthCardLinks>
              <Link className="link hover:link-primary" to="/sign-in">
                Sign In
              </Link>
              or
              <Link className="link hover:link-primary" to="/sign-up">
                Sign Up
              </Link>
            </AuthCardLinks>
          </AuthCardActions>
        </ValidatedForm>
      </AuthCardBody>
    </AuthCard>
  );
}

// src/pages/password-reset.vue
<script setup lang="ts">
definePageMeta({
  auth: {
    unauthenticatedOnly: true,
  },
});

import * as z from "zod";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";

const validationSchema = toTypedSchema(
  z.object({
    email: z
      .string()
      .min(1, { message: "Email is required." })
      .email("Must be a valid email."),
  }),
);

const {
  handleSubmit,
  errors,
  isSubmitting,
  setFieldValue,
  values,
  submitCount,
} = useForm({
  validationSchema,
});

const isEmailSent = ref(false);

const onSubmit = handleSubmit(async () => {
  // TODO: This has to live on the server
  // await sendPasswordResetEmail(auth, values.email);
});

function handleOnInput(field: keyof typeof values, event: Event) {
  setFieldValue(
    field,
    (event.currentTarget as HTMLInputElement).value,
    submitCount.value > 0,
  );
}
</script>

<template>
  <AuthCard v-if="isEmailSent">
    <AuthCardBody>
      <P class="alert alert-info shadow-lg mb-3">
        Please check your email for a reset password link.
      </P>

      <div class="flex justify-end gap-1">
        <Link class="link hover:link-primary" to="/sign-in"> Sign In </Link>
        or
        <Link class="link hover:link-primary" to="/sign-up"> Sign Up </Link>
      </div>
    </AuthCardBody>
  </AuthCard>
  <AuthCard v-else>
    <AuthCardBody>
      <form novalidate @submit="onSubmit">
        <AuthCardTitle>Reset Password</AuthCardTitle>

        <TextField
          :error="submitCount > 0 ? errors.email : undefined"
          :on-input="(event) => handleOnInput('email', event)"
          :value="values.email"
          label="Email"
          name="email"
          type="email"
        />

        <AuthCardActions>
          <SubmitButton :is-loading="isSubmitting" :disabled="isSubmitting">
            <span v-if="isSubmitting">Sending Reset Email...</span>
            <span v-else>Reset Password</span>
          </SubmitButton>

          <AuthCardLinks>
            <NuxtLink class="link hover:link-primary" to="/sign-in">
              Sign In
            </NuxtLink>
            or
            <NuxtLink class="link hover:link-primary" to="/sign-up">
              Sign Up
            </NuxtLink>
          </AuthCardLinks>
        </AuthCardActions>
      </form>
    </AuthCardBody>
  </AuthCard>
</template>
