// app/routes/sign-up.tsx
import type { ActionArgs } from "@remix-run/node";
import { redirect } from "@remix-run/node";
import { Link, useLocation, useTransition } from "@remix-run/react";
import { withZod } from "@remix-validated-form/with-zod";
import { createUserWithEmailAndPassword } from "firebase/auth";
import { ValidatedForm, validationError } from "remix-validated-form";
import { z } from "zod";
import { SubmitButton } from "~/components/submit-button";
import { TextField } from "~/components/text-field";
import {
  AuthCard,
  AuthCardActions,
  AuthCardBody,
  AuthCardLinks,
  AuthCardTitle,
  getRedirectURL,
} from "~/features/auth";
import { auth } from "~/lib/firebase";

const validator = withZod(
  z.object({
    email: z
      .string()
      .min(1, { message: "Email is required." })
      .email("Must be a valid email."),
    password: z.string().min(1, "Password is required."),
  })
);

export async function action({ request }: ActionArgs) {
  const formData = await request.formData();

  const result = await validator.validate(formData);

  if (result.error) {
    return validationError(result.error);
  }

  const { email, password } = result.data;

  await createUserWithEmailAndPassword(auth, email, password);

  return redirect(getRedirectURL({ request }));
}

export default function SignUp() {
  const { submission } = useTransition();
  const location = useLocation();

  return (
    <AuthCard>
      <AuthCardBody>
        <ValidatedForm validator={validator} method="post">
          <AuthCardTitle>Sign Up</AuthCardTitle>

          <TextField name="email" type="email" label="Email" />
          <TextField name="password" type="password" label="Password" />

          <AuthCardActions>
            <SubmitButton
              isLoading={Boolean(submission)}
              disabled={Boolean(submission)}
            >
              {submission ? "Signing Up..." : "Sign Up"}
            </SubmitButton>

            <AuthCardLinks>
              <Link
                className="link hover:link-primary"
                to={getRedirectURL({ location })}
              >
                Sign In
              </Link>
              or
              <Link className="link hover:link-primary" to="/password-reset">
                Reset Password
              </Link>
            </AuthCardLinks>
          </AuthCardActions>
        </ValidatedForm>
      </AuthCardBody>
    </AuthCard>
  );
}

// src/pages/sign-up.vue
<script setup lang="ts">
import { toTypedSchema } from "@vee-validate/zod";
import { useForm, PublicPathState } from "vee-validate";
import { z } from "zod";
import { SignUpErrors } from "~/server/api/sign-up.post";

const { $toast } = useNuxtApp();

definePageMeta({
  auth: {
    unauthenticatedOnly: true,
  },
});

const validationSchema = toTypedSchema(
  z.object({
    email: z
      .string({ required_error: "Email is required." })
      .email("Must be a valid email."),
    password: z.string({ required_error: "Password is required." }),
  }),
);

const { defineComponentBinds, handleSubmit, isSubmitting } = useForm({
  validationSchema,
});

const defineComponentBindsOptions = {
  model: "value",
  mapProps: ({ errors }: PublicPathState) => ({ errors }),
};

const email = defineComponentBinds("email", defineComponentBindsOptions);
const password = defineComponentBinds("password", defineComponentBindsOptions);

const errors = ref<null | SignUpErrors>(null);

const onSubmit = handleSubmit(async (values) => {
  const result = await $fetch("/api/sign-up", {
    method: "POST",
    body: values,
  });

  if (result.success) {
    await $toast.show({ message: "Sign up successful. Please sign in." });
    await navigateTo(`/sign-in?email=${values.email}`);
  } else {
    errors.value = result.error;
  }
});
</script>

<template>
  <AuthCard>
    <AuthCardBody>
      <form novalidate @submit="onSubmit">
        <AuthCardTitle>Sign Up</AuthCardTitle>

        <TextField v-bind="email" label="Email" name="email" type="email" />

        <TextField
          v-bind="password"
          label="Password"
          name="password"
          type="password"
        />

        <P
          v-for="error in errors?.formErrors"
          :key="error"
          class="alert alert-error shadow-lg mb-3"
          >{{ error }}</P
        >

        <AuthCardActions>
          <SubmitButton :is-loading="isSubmitting" :disabled="isSubmitting"
            >Sign Up</SubmitButton
          >

          <AuthCardLinks>
            <NuxtLink class="link hover:link-primary" to="/sign-in">
              Sign In
            </NuxtLink>
            or
            <NuxtLink class="link hover:link-primary" to="/password-reset">
              Reset Password
            </NuxtLink>
          </AuthCardLinks>
        </AuthCardActions>
      </form>
    </AuthCardBody>
  </AuthCard>
</template>
