// app/routes/sign-in.tsx
import type { ActionArgs, LoaderArgs } from "@remix-run/node";
import { Link, useCatch, useTransition } from "@remix-run/react";
import { withZod } from "@remix-validated-form/with-zod";
import { ValidatedForm, validationError } from "remix-validated-form";
import { z } from "zod";
import { SubmitButton } from "~/components/submit-button";
import { TextField } from "~/components/text-field";
import {
  AuthCard,
  AuthCardActions,
  AuthCardBody,
  AuthCardLinks,
  AuthCardTitle,
} from "~/features/auth";
import { authenticator } from "~/services/auth.server";

const validator = withZod(
  z.object({
    email: z
      .string()
      .min(1, { message: "Email is required." })
      .email("Must be a valid email."),
    password: z.string().min(1, "Password is required."),
  })
);

export async function action({ request }: ActionArgs) {
  const clone = request.clone();
  const formData = await clone.formData();

  const result = await validator.validate(formData);

  if (result.error) {
    return validationError(result.error);
  }

  return await authenticator.authenticate("user-pass", request, {
    successRedirect: "/",
  });
}

export async function loader({ request }: LoaderArgs) {
  return await authenticator.isAuthenticated(request, {
    successRedirect: "/",
  });
}

export function CatchBoundary() {
  const caught = useCatch();

  return <SignIn message={caught.data.message} />;
}

export default function SignIn({ message }: { message?: string }) {
  const { submission } = useTransition();

  return (
    <AuthCard>
      <AuthCardBody>
        <ValidatedForm validator={validator} method="post">
          <AuthCardTitle>Sign In</AuthCardTitle>

          <TextField name="email" type="email" label="Email" />
          <TextField name="password" type="password" label="Password" />

          {message ? (
            <p className="alert alert-error shadow-lg mb-3">{message}</p>
          ) : null}

          <AuthCardActions>
            <SubmitButton
              isLoading={Boolean(submission)}
              disabled={Boolean(submission)}
            >
              {submission ? "Signing In..." : "Sign In"}
            </SubmitButton>

            <AuthCardLinks>
              <Link className="link hover:link-primary" to="/sign-up">
                Sign Up
              </Link>
              or
              <Link className="link hover:link-primary" to="/password-reset">
                Reset Password
              </Link>
            </AuthCardLinks>
          </AuthCardActions>
        </ValidatedForm>
      </AuthCardBody>
    </AuthCard>
  );
}

// src/pages/sign-in.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";

const validationSchema = toTypedSchema(
  z.object({
    email: z
      .string()
      .min(1, { message: "Email is required." })
      .email("Must be a valid email."),
    password: z.string().min(1, "Password is required."),
  }),
);

const {
  handleSubmit,
  errors,
  isSubmitting,
  setFieldValue,
  values,
  submitCount,
} = useForm({
  validationSchema,
});

const { signIn } = useAuth();
const route = useRoute();

const onSubmit = handleSubmit(async (values) => {
  await signIn("credentials", {
    ...values,
    callbackUrl:
      typeof route.query.callbackUrl === "string"
        ? route.query.callbackUrl
        : "/",
  });
});

function handleOnInput(field: keyof typeof values, event: Event) {
  setFieldValue(
    field,
    (event.currentTarget as HTMLInputElement).value,
    submitCount.value > 0,
  );
}
</script>

<template>
  <AuthCard>
    <AuthCardBody>
      <form novalidate @submit="onSubmit">
        <AuthCardTitle>Sign In</AuthCardTitle>

        <TextField
          :error="submitCount > 0 ? errors.email : undefined"
          :on-input="(event) => handleOnInput('email', event)"
          :value="values.email"
          label="Email"
          name="email"
          type="email"
        />

        <TextField
          :error="submitCount > 0 ? errors.password : undefined"
          :on-input="(event) => handleOnInput('password', event)"
          :value="values.password"
          label="Password"
          name="password"
          type="password"
        />

        <P
          v-if="route.query.error === 'CredentialsSignin'"
          class="alert alert-error shadow-lg mb-3"
          >Incorrect sign in credentials.</P
        >

        <AuthCardActions>
          <SubmitButton :is-loading="isSubmitting" :disabled="isSubmitting">
            Sign In
          </SubmitButton>

          <AuthCardLinks>
            <NuxtLink class="link hover:link-primary" to="/sign-up">
              Sign Up
            </NuxtLink>
            or
            <NuxtLink class="link hover:link-primary" to="/password-reset">
              Reset Password
            </NuxtLink>
          </AuthCardLinks>
        </AuthCardActions>
      </form>
    </AuthCardBody>
  </AuthCard>
</template>
