// src/pages/password-update.vue
<script setup lang="ts">
definePageMeta({
  auth: {
    unauthenticatedOnly: true,
  },
});

import { toTypedSchema } from "@vee-validate/zod";
import { FirebaseError } from "firebase/app";
import { useForm } from "vee-validate";
import * as z from "zod";
import {
  codeSchema,
  passwordSchema,
  componentBindsConfig,
} from "~/features/forms";
import { PasswordUpdateErrors } from "~/server/api/password-update";
import { FetchError } from "ofetch";

const { query } = useRoute();
const { push } = useRouter();

const validationSchema = toTypedSchema(
  z.object({
    code: codeSchema,
    password: passwordSchema,
  }),
);

const { handleSubmit, setErrors, isSubmitting, values, defineComponentBinds } =
  useForm({
    validationSchema,
    initialValues: {
      code: typeof query.oobCode === "string" ? query.oobCode : undefined,
    },
  });

const code = defineComponentBinds("code", componentBindsConfig);
const password = defineComponentBinds("password", componentBindsConfig);

const formErrors = ref<null | PasswordUpdateErrors["formErrors"]>(null);

const onSubmit = handleSubmit(async () => {
  formErrors.value = [];

  try {
    await $fetch("/api/password-update", {
      method: "POST",
      body: values,
    });

    push("/sign-in");
  } catch (error) {
    if (error instanceof FetchError) {
      const data: FetchError<PasswordUpdateErrors>["data"] = error.data;

      formErrors.value = data?.formErrors || null;

      setErrors(data?.fieldErrors || {});

      return;
    }

    throw error;
  }
});
</script>

<template>
  <AuthCard>
    <AuthCardBody>
      <form novalidate @submit="onSubmit">
        <AuthCardTitle>Update Password</AuthCardTitle>

        <TextField v-bind="code" name="code" type="hidden" />
        <TextField
          v-bind="password"
          label="Password"
          name="password"
          type="password"
        />

        <P
          v-for="error in formErrors"
          :key="error"
          class="alert alert-error shadow-lg mb-3"
          >{{ error }}</P
        >

        <input type="hidden" name="code" :value="{ code }" />

        <AuthCardActions>
          <SubmitButton :is-loading="isSubmitting" :disabled="isSubmitting">
            <span v-if="isSubmitting">Updating Password...</span>
            <span v-else>Update Password</span>
          </SubmitButton>
        </AuthCardActions>
      </form>
    </AuthCardBody>
  </AuthCard>
</template>

// app/routes/password-update.tsx
import type { ActionArgs, LoaderArgs } from "@remix-run/node";
import { json, redirect } from "@remix-run/node";
import { useActionData, useLoaderData, useTransition } from "@remix-run/react";
import { withZod } from "@remix-validated-form/with-zod";
import { FirebaseError } from "firebase/app";
import { confirmPasswordReset } from "firebase/auth";
import { ValidatedForm, validationError } from "remix-validated-form";
import { z } from "zod";
import { SubmitButton } from "~/components/submit-button";
import { TextField } from "~/components/text-field";
import { P } from "~/components/typeography/p";
import {
  AuthCard,
  AuthCardActions,
  AuthCardBody,
  AuthCardTitle,
  getRedirectURL,
} from "~/features/auth";
import { auth } from "~/lib/firebase";
import { getErrorMessage } from "~/lib/firebase-errors";

const validator = withZod(
  z.object({
    code: z.string().min(1, { message: "Reset code is required." }),
    password: z.string().min(1, "Password is required."),
  })
);

export async function action({ request }: ActionArgs) {
  const formData = await request.formData();

  const result = await validator.validate(formData);

  if (result.error) {
    return validationError(result.error);
  }

  const { code, password } = result.data;

  try {
    await confirmPasswordReset(auth, code, password);
  } catch (error) {
    if (error instanceof FirebaseError) {
      return json(
        {
          errorMessage: getErrorMessage(error.code),
        },
        {
          status: 400,
          statusText: "Bad Request",
        }
      );
    }
  }

  return redirect(getRedirectURL({ request }));
}

export async function loader({ request }: LoaderArgs) {
  const url = new URL(request.url);
  const code = url.searchParams.get("oobCode");

  if (!code) {
    return json(
      { errorMessage: "Reset code is required." },
      { status: 400, statusText: "Bad Request" }
    );
  }

  return json({ code });
}

export default function PasswordUpdate() {
  const data = useActionData<typeof action>();
  const loaderData = useLoaderData<typeof loader>();
  const { submission } = useTransition();

  return (
    <AuthCard>
      <AuthCardBody>
        <ValidatedForm validator={validator} method="post">
          <AuthCardTitle>Update Password</AuthCardTitle>

          <TextField name="password" type="password" label="New Password" />

          {loaderData && "errorMessage" in loaderData ? (
            <P className="alert alert-error shadow-lg mb-3">
              {loaderData.errorMessage}
            </P>
          ) : (
            <input type="hidden" name="code" value={loaderData.code} />
          )}

          {data && "errorMessage" in data ? (
            <P className="alert alert-error shadow-lg mb-3">
              {data.errorMessage}
            </P>
          ) : null}

          <AuthCardActions>
            <SubmitButton
              isLoading={Boolean(submission)}
              disabled={Boolean(submission)}
            >
              {submission ? "Updating Password..." : "Update Password"}
            </SubmitButton>
          </AuthCardActions>
        </ValidatedForm>
      </AuthCardBody>
    </AuthCard>
  );
}
